POST http://localhost:2525/imposters
Content-Type: application/json

{
    "name": "Ex10",
    "port": 4557,
    "protocol": "http",
    "stubs": [
        {
            "predicates": [
                {
                    "equals":{
                        "method": "POST",
                        "path": "/api/tasks"
                    }
                },
                {
                    "matches": {
                        "body": "\"title\"\\s*:\\s*\"duplicate\""
                    }
                }
            ],
            "responses": [
                {
                    "is": {
                        "statusCode": 409,
                        "headers": {
                            "Content-Type": "application/json"
                        },
                        "body": {
                            "error": "duplicate_task"
                        }
                    }
                }
            ]
        }
    ]
}

###

POST http://localhost:4557/api/tasks
Content-Type: application/json

{
    "title": "duplicate"
}
