POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name": "Ex7",
  "port": 4554,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/users"
          }
        },
        {
          "contains": {
            "body": "\"email\":\"exists@example.com\""
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 409,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "email_exists",
              "message": "Esse email já existe."
            }
          }
        }
      ]
    },
    {
    "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/users"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
                "id":123,
                "status": "Created",
                "message": "User criado com sucesso."
            }
          }
        }
      ]
    }
  ]
}

###

POST http://localhost:4554/api/users
Content-Type: application/json

{
    "name":"Guilherme",
    "idade":16,
    "email":"teste@example.com"
}
