POST http://localhost:2525/imposters
Content-Type: application/json
 
{
  "port": 4545,
  "protocol": "http",
  "stubs": [{
    "responses": [
      { "is": { "statusCode": 200 }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/test",
            "method": "POST",
            "headers": { "Content-Type": "application/json" }
          }
        },
        {
          "not": {
            "contains": { "body": "requiredField" },
            "caseSensitive": true
          }
        }
      ]
    }]
  }]
}
 
###
 
POST http://localhost:4545/test
 
Content-Type: application/json
{"optionalField": true}
 
###
 
POST http://localhost:2525/imposters
Content-Type: application/json
 
{
  "name":"API 2",
  "port": 4546,
  "protocol": "http",
  "stubs": [{
    "responses": [
      { "is": { "statusCode": 200,
                "body": {
                  "marca": "BMW",
                  "Modelo": "M4"
                }
      }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/test",
            "method": "POST",
            "headers": { "Content-Type": "application/json" }
          }
        },
        {
          "not": {
            "contains": { "body": "requiredField" },
            "caseSensitive": true
          }
        }
      ]
    }]
  }]
}
