POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name": "2 Ex3",
  "port": 4565,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/reservas"
          }
        },
        {
          "contains": {
            "body": "\"checkout\":\"2025-06-18\""
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 400,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "checkout anterior ao checkin"
            }
          }
        }
      ]
    },
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/reservas"
          }
        },
        {
          "contains": {
            "body": "\"tipo_quarto\":\"suite\""
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 409,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "Sem disponibilidade"
            }
          }
        }
      ]
    },
    {
      "predicates": [
        {
          "equals": {
            "method": "GET",
            "path": "/api/reservas"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": [
              {
                "id": 1,
                "cliente": "Joao",
                "tipo_quarto": "single"
              }
            ]
          }
        }
      ]
    },
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/reservas"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": {
              "Content-Type": "application/json",
              "Location": "/api/reservas/1"
            },
            "body": {
              "id": 1,
              "status": "created"
            }
          }
        }
      ]
    }
  ]
}

###
POST http://localhost:4565/api/reservas
Content-Type: application/json

{
  "cliente":"Joao",
  "checkin":"2025-06-20",
  "checkout":"2025-06-22",
  "tipo_quarto":"single"
}